/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as ErrorImport } from './routes/error'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as BookingListImport } from './routes/bookingList'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BookingListRoute = BookingListImport.update({
  id: '/bookingList',
  path: '/bookingList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookingList': {
      id: '/bookingList'
      path: '/bookingList'
      fullPath: '/bookingList'
      preLoaderRoute: typeof BookingListImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookingList': typeof BookingListRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookingList': typeof BookingListRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bookingList': typeof BookingListRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookingList'
    | '/dashboard'
    | '/error'
    | '/login'
    | '/logout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookingList' | '/dashboard' | '/error' | '/login' | '/logout'
  id:
    | '__root__'
    | '/'
    | '/bookingList'
    | '/dashboard'
    | '/error'
    | '/login'
    | '/logout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingListRoute: typeof BookingListRoute
  DashboardRoute: typeof DashboardRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingListRoute: BookingListRoute,
  DashboardRoute: DashboardRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bookingList",
        "/dashboard",
        "/error",
        "/login",
        "/logout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bookingList": {
      "filePath": "bookingList.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
